### PR TITLE
Prepare for v1.3 release

### PR DESCRIPTION
**Pull request by ChrisMaddock**
This is the v1.3 release branch, ready for review. There is a draft release [here](https://github.com/nunit/nunit-vs-templates/releases/tag/untagged-b7076b4700f82e4d393c).

Remaining tasks after review:

 - [x] Make release public
 - [x] Push to VS Gallery, and update extension overview with [this gist](https://gist.github.com/ChrisMaddock/4f829f67527a9e08e7450575fbef3d97). (No changes except removing WinPhone 8.1 and a typo.)
- [x] Merge https://github.com/nunit/nunit.org/pull/56 and reupload website

Post-release, I will..
 - [ ] Update version numbers for 1.4

@rprouse - the rest is over to you. 😄 Let me know if I've missed anything - no rush on this one at all.

### CODE REVIEW

**Comment by rprouse** [comment]
This all looks good. @ChrisMaddock would you like me to make the final release? I don't mind doing it, just checking. I am guessing you do because you don't have upload permissions on the marketplace.

**Comment by ChrisMaddock** [comment]
Yes please! 😄 I've already attached the .vsix to the draft GitHub release. I just don't have access to upload it to the marketplace, or push the NUnit website.

**Comment by rprouse** [comment]
This has been released, It just takes awhile for the extension to update on the new marketplace. You still upload on the old and it gets synced to the new at https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnitTemplatesforVisualStudio

I am going to merge, but we should watch the above link to make sure it comes through.

I tested installing in 2013, 2015 and 2017. The marketplace also looked at it and says it supports 2012.

**Comment by rprouse** [comment]
We won't delete this release branch.

**Comment by rprouse** [comment]
The extension has been synced to the marketplace and looks good.

**Comment by ChrisMaddock** [comment]
Great - thanks Rob!

**Pull request merged**
